In [5]:
import numpy as np
import matplotlib.pylab as plt
import sympy as sp
from scipy.integrate import odeint, complex_ode
from tqdm import tqdm
import cmath

In [10]:
k = 300
k_inj = k
a = 3
mu = 4
gamma_p = 192.1
gamma_a = 1
gamma_s = 1000
gamma_e = 1
        
def F(s, t):
        rE_x = s[0]
        cE_x = s[1]
        rE_y = s[2]
        cE_y = s[3]
        rD = s[4]
        cD = s[5]
        rn = s[6]
        cn = s[7]
        delta_w = gamma_p / 3.14

        dERxdt = k*(rD*rE_x - cE_x * cD - rn*cE_y - cn*rE_y - rE_x) + a*k*(rE_x*cD - cE_x*rD - rn*rE_y+cE_y*cn + cE_x) - (gamma_p + delta_w) * rE_x - gamma_a*cE_x
        dECxdt = k*(rE_x*cD + cE_x*rD +rn*rE_y - cE_y*cn - cE_x) + a*k*(rD*rE_x - cD*cE_x - rn*cE_y -cn*rE_y - rE_x) - (gamma_p + delta_w)*cE_x - gamma_a*(rE_x )
        
        dERydt = k*(rD*rE_y - cE_y * cD +rn*cE_x + cn*rE_x - rE_y) + a*k*(-rE_y*cD - cE_y*rD + rn*rE_x+cE_x*cn + cE_y) - (gamma_p - delta_w) * rE_y + gamma_a*cE_y
        dECydt = k*(rE_y*cD + cE_y*rD - rn*rE_x + cE_x*cn - cE_y) + a*k*(rE_y*rD - cD*cE_y + rn*cE_y - rE_y) - (gamma_p - delta_w)*cE_y - gamma_a*(rE_y)

        dDRdt = - gamma_e * (rD*(1 +(rE_x)**2 + (cE_x)**2) + (rE_y)**2 + (cE_y**2)) + gamma_e * mu - gamma_e * (rn*cE_y*rE_x + rn*cE_x*rE_y - rn*cE_y*rE_x - cn*rE_y*rE_x - cn*cE_x*cE_y +cn*rE_y*rE_y + cn*cE_y*cE_x + cn*cE_x*rE_y)
        dDCdt = - gamma_e * (cD*(1 +(rE_x)**2 + (cE_x)**2)) - gamma_e * (rn*rE_y*rE_x + rn * cE_x * cE_y - rn* rE_x *rE_y - rn * cE_y * cE_x - cn*cE_y*rE_y + cn * cE_x*rE_y - cn*cE_y*rE_x)
        
        dnRdt = gamma_e * ( - rn*cE_y*rE_x + rn*cE_x*rE_y + rn*cE_x*rE_y - rn*cE_y*rE_x - cn*rE_y*rE_x - cn*cE_x*cE_y + cn*rE_x*rE_y +cn*cE_y*cE_x + cn*cE_x*rE_y) - gamma_s*(rn) - gamma_e*(rn * ((rE_x)**2 +(cE_x)**2 + (rE_y)**2 +(cE_y)**2))
        dnCdt = gamma_e * (rn*rE_y*rE_x + rn*cE_x*cE_y - rn*rE_x*rE_y - rn*cE_y*cE_x - cn*cE_y*rE_x + cn*cE_x * rE_y) - gamma_s *cn - gamma_e*(cn*((rE_x)**2 +(cE_x)**2 + (rE_y)**2 +(cE_y)**2))
        
        return [dERxdt, dECxdt, dERydt, dECydt, dDRdt, dDCdt, dnRdt, dnCdt]

In [11]:
def solve_ode(mu, E_inj, st0):
    t = np.linspace(0.0, 105.0, 1000000)
    st = odeint(F, st0, t)
    return st[0], st[1], st[2], st[3], st[4], st[5], st[6], st[7]

In [12]:
solve_ode(3, 0, [0, 0 ,0 ,0 ,0 ,0 ,0, 0])

(array([0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0.        , 0.        , 0.        , 0.        , 0.00041998,
        0.        , 0.        , 0.        ]),
 array([0.        , 0.        , 0.        , 0.        , 0.00083991,
        0.        , 0.        , 0.        ]),
 array([0.       , 0.       , 0.       , 0.       , 0.0012598, 0.       ,
        0.       , 0.       ]),
 array([0.        , 0.        , 0.        , 0.        , 0.00167965,
        0.        , 0.        , 0.        ]),
 array([0.        , 0.        , 0.        , 0.        , 0.00209945,
        0.        , 0.        , 0.        ]),
 array([0.        , 0.        , 0.        , 0.        , 0.00251921,
        0.        , 0.        , 0.        ]),
 array([0.        , 0.        , 0.        , 0.        , 0.00293892,
        0.        , 0.        , 0.        ]))

In [5]:
len(set(list(range(-5,5))+list(range(-8,5))))

13